export const booleanProps = [
    'allowHTML',
    'arrow',
    'flip',
    'flipOnUpdate',
    'hideOnClick',
    'ignoreAttributes',
    'inertia',
    'interactive',
    'lazy',
    'multiple',
    'showOnCreate',
    'touch',
];

export const methodProps = [
    'onAfterUpdate',
    'onBeforeUpdate',
    'onCreate',
    'onDestroy',
    'onHidden',
    'onHide',
    'onMount',
    'onShow',
    'onShown',
    'onTrigger',
    'onUntrigger',
];

export const props = [
    'animation',
    'appendTo',
    'aria',
    'boundary',
    'content',
    'delay',
    'distance',
    'duration',
    'flipBehavior',
    'interactiveBorder',
    'interactiveDebounce',
    'maxWidth',
    'offset',
    'placement',
    'plugins',
    'popperOptions',
    'role',
    'theme',
    'trigger',
    'triggerTarget',
    'updateDuration',
    'zIndex',
    ...booleanProps,
    ...methodProps,
];